### ISSUE TITLE
Would be nice to update the receivers list trough socket js

### ISSUE THREAD

**Issue by mylastore** [nehalist/Realtime-Notifications#1]
This is more like a feature 👍  great job tho the notifications and message I been trying to do this my self but could not get the template to update. Thank so much more this repo.

**Comment by nehalist** [comment]
Hey @mylastore, thanks for the kind words.

This would indeed be a feature, but I'll probably update this entire repository as soon as Sails hits `v1.0`. Since there'll be some breaking changes it's probably the best to just wait.

**Comment by mylastore** [comment]
Make sense thanks.
